### ISSUE TITLE
works not showing up on GitHub: check xPath, adjust hook test

### ISSUE THREAD

**Issue by annettegessner** [PerseusDL/Nemo#14]
Here are the links to some of the works, that are not showing up on GitHub:
http://perseus-nemo.herokuapp.com/read/latinLit/stoa0162/stoa024/opp-lat1
http://perseus-nemo.herokuapp.com/read/latinLit/stoa0162/stoa004/opp-lat2
http://perseus-nemo.herokuapp.com/read/latinLit/stoa0162/stoa004/opp-lat3
http://perseus-nemo.herokuapp.com/read/latinLit/stoa0162/stoa004/opp-lat1
http://perseus-nemo.herokuapp.com/read/latinLit/stoa0149b/stoa002/opp-lat1

Thibault wrote, this might be an issue with the xPath and the hook test needs to be adjusted to check, if lower levels have deeper xPath. (E.g.: citation node states letter > section > chapter, but chapter does not take section into account.) 
http://services2.perseids.org/exist/restxq/cts?inv=nemo&request=GetValidReff&urn=urn:cts:latinLit:stoa0162.stoa004.opp-lat1&level=3 "

Removing @subtype in the xPath might help.

**Comment by PonteIneptique** [comment]
This issue should not be open in Nemo but in CSEL I'd say :)

**Comment by PonteIneptique** [comment]
And one in Capitains/HookTest for the citation length difference :)

**Comment by annettegessner** [comment]
You are right, @PonteIneptique! I added one issue on CSEL (#277). Would you be so kind and write one for Capitains/HookTest? I think, you can do this more precise than me. Thanks!
